Initial setup for cookiecutter template

diff --git a/{{ cookiecutter.__project_slug }}/.github/workflows/release.yml b/{{ cookiecutter.__project_slug }}/.github/workflows/release.yml
--- a/{{ cookiecutter.__project_slug }}/.github/workflows/release.yml
+++ b/{{ cookiecutter.__project_slug }}/.github/workflows/release.yml
@@ -9,12 +9,12 @@ jobs:
     environment:
       name: release
     outputs:
-      release_version: {% raw -%}${{ steps.get_version.outputs.release_version }}{% endraw %}
+      release_version: ${{ steps.get_version.outputs.release_version }}
     steps:
       - name: Get version from branch name
         id: get_version
         run: |
-          branch_name={% raw -%}${{ github.ref_name }}{% endraw %}
+          branch_name=${{ github.ref_name }}
           release_version="${branch_name##release/}"
           if [ "${release_version}" == "${branch_name}" ]; then
             echo "Invalid branch name: ${branch_name}"
@@ -28,12 +28,12 @@ jobs:
     environment:
       name: release
     outputs:
-      pypi_version: {% raw -%}${{ steps.get_pypi_version.outputs.pypi_version }}{% endraw %}
+      pypi_version: ${{ steps.get_pypi_version.outputs.pypi_version }}
     steps:
       - name: Fetch information from PyPI
         id: get_pypi_version
         run: |
-          response=$(curl -s https://pypi.org/pypi/{% raw -%}${{ github.event.repository.name }}{% endraw %}/json || echo "{}")
+          response=$(curl -s https://pypi.org/pypi/${{ github.event.repository.name }}/json || echo "{}")
           pypi_version=$(echo $response | jq --raw-output "select(.releases != null) | .releases | keys_unsorted | last")
           if [ -z "$pypi_version" ]; then
             echo "Package not found on PyPI."
@@ -46,12 +46,12 @@ jobs:
     needs: [get_version_from_branch_name, pypi_version]
     runs-on: ubuntu-latest
     outputs:
-      release_version: {% raw -%}${{ steps.version.outputs.release_version }}{% endraw %}
+      release_version: ${{ steps.version.outputs.release_version }}
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: "3.x"
 
@@ -62,8 +62,8 @@ jobs:
       - name: Compare current version with PyPI version
         id: version
         run: |
-          release_version={% raw -%}${{ needs.get_version_from_branch_name.outputs.release_version }}{% endraw %}
-          pypi_version={% raw -%}${{ needs.pypi_version.outputs.pypi_version }}{% endraw %}
+          release_version=${{ needs.get_version_from_branch_name.outputs.release_version }}
+          pypi_version=${{ needs.pypi_version.outputs.pypi_version }}
           repo_version=$(hatch version)
           
           if [ "$release_version" == "$pypi_version" ]; then
@@ -82,7 +82,7 @@ jobs:
           if [ "${release_version}" != "${repo_version}" ]; then
             higher_version=$(printf '%s\n' "$release_version" "$repo_version" | sort -rV | head -n 1)
             if [ "$higher_version" != "$release_version" ]; then
-              echo "Error! Version ${release_version} is lower than repository version ${repo_version} on PyPI"
+              echo "Error! Version ${release_version} is lower than repository version ${repo_version}"
               exit 1
             fi
             echo "Repository version was ${repo_version}. Updating to ${release_version}"
@@ -94,13 +94,13 @@ jobs:
 
 
       - name: Build source and wheel distribution
-        if: {% raw -%}${{ steps.version.outputs.release_version }}{% endraw %}
+        if: ${{ steps.version.outputs.release_version }}
         run: |
           hatch build
 
       - name: Upload artifacts
-        if: {% raw -%}${{ steps.version.outputs.release_version }}{% endraw %}
-        uses: actions/upload-artifact@v3
+        if: ${{ steps.version.outputs.release_version }}
+        uses: actions/upload-artifact@v4
         with:
           name: dist
           path: dist/
@@ -108,9 +108,9 @@ jobs:
   github_tag:
     name: Create GitHub tag
     needs: [build_package]
-    if: {% raw -%}${{ needs.build_package.outputs.release_version }}{% endraw %}
+    if: ${{ needs.build_package.outputs.release_version }}
     outputs:
-      tag_name: {% raw -%}${{ steps.construct_tag_name.outputs.tag_name }}{% endraw %}
+      tag_name: ${{ steps.construct_tag_name.outputs.tag_name }}
     runs-on: ubuntu-latest
     environment:
       name: release
@@ -118,7 +118,7 @@ jobs:
       - name: Construct tag name
         id: construct_tag_name
         run: |
-          tag_name=v{%raw -%}${{ needs.build_package.outputs.release_version }}{% endraw %}
+          tag_name=v${{ needs.build_package.outputs.release_version }}
           echo "Making new tag ${tag_name}"
           echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
       - name: Create tag
@@ -128,14 +128,14 @@ jobs:
             github.rest.git.createRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
-              ref: 'refs/tags/{% raw -%}${{ steps.construct_tag_name.outputs.tag_name }}{% endraw %}',
+              ref: 'refs/tags/${{ steps.construct_tag_name.outputs.tag_name }}',
               sha: context.sha
             })
 
   github_release:
     name: Create GitHub Release
     needs: [github_tag]
-    if: {% raw -%}${{ needs.github_tag.outputs.tag_name }}{% endraw %}
+    if: ${{ needs.github_tag.outputs.tag_name }}
     runs-on: ubuntu-latest
     environment:
       name: release
@@ -143,12 +143,12 @@ jobs:
       contents: write
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
       - name: Download artifacts
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: dist
           path: dist/
@@ -156,24 +156,24 @@ jobs:
       - name: Create GitHub Release
         id: create_release
         env:
-          GH_TOKEN: {% raw -%}${{ github.token }}{% endraw %}
+          GH_TOKEN: ${{ github.token }}
         run: |
-          tag_name={% raw -%}${{ needs.github_tag.outputs.tag_name }}{% endraw %}
+          tag_name=${{ needs.github_tag.outputs.tag_name }}
           gh release create ${tag_name} dist/* --title "Release ${tag_name}" --notes-file CHANGELOG.md
 
   pypi_publish:
     name: Upload release to PyPI
     needs: [github_release, github_tag]
-    if: {% raw -%}${{ needs.github_tag.outputs.tag_name }}{% endraw %}
+    if: ${{ needs.github_tag.outputs.tag_name }}
     runs-on: ubuntu-latest
     environment:
       name: release
-      url: https:/pypi.org/p/{{ cookiecutter.__project_slug }}
+      url: https:/pypi.org/p/${{ github.event.repository.name }}
     permissions:
       id-token: write
     steps:
       - name: Download artifacts
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: dist
           path: dist/
